
function characterGen () {

var arrNames = [
"tobin",
"meer",
"finn",
"Chaunsey",
"Varlette",
"Dansey",
"Meisse",
"Ding",
"Uwert",
"Meincice",
"Iovan",
"Oesgeese",
"Loesse",
"Wahler",
"Menud",
"Giselt",
"Pawren",
"Ellys",
"Denys",
"Orronomo",
"Jhieng",
"Direc",
"Jiames",
"Solomon",
"Emilie",
"Simone",
"Giscard",
"Dickery",
"Opsley",
"Peesmake",
"Eppington",
"Slater",
"Marmery",
"Lockdell",
"Go-Whitting",
"Chuckslee",
"Cooper",
"Olivet",
"Warde",
"Deckart",
"Peacher",
"Elmswood",
"Fallada",
"Giscert",
"Pickles",
"Morsley",
"Onlylle",
"Streder",
"Kade",
"Steke",
"Clere",
"Dorvey",
"Ann",
"Aura",
"Kimbo",
"Geggs",
"Maeter",
"Caesegyrt",
"Tyggs",
"Giesel",
"Derryn",
"Ilien",
"Verucia",
"Porto",
"Totian",
"Liovan",
"Merrys",
"Osmyn",
"Orhen",
"Oyzze",
"Juilliet",
"Silend",
"Dellys",
"Benet",
"Laszolo",
"Orenne",
"Limey",
"Lauret",
"Willon",
"Maisley",
"Porta",
"Teyen",
"Atillio",
"Sibilla",
"Giossa",
"Barbro",
"Ermolao",
"Boellielli",
"Detto",
"Magni",
"Corrado",
"Cecco",
"Aloian",
"Bardil",
"Croce",
"Drigo",
"Arrico",
"Dina",
"Evola",
"Garallo",
"Brunhi",
"Lussu",
"Gienna",
"Rhanca",
"Zaccaro",
"Ales",
"Zmitra",
"Zmito",
"Maksima",
"Vasil",
"Ciotko",
"Bykau",
"Barad",
"Ardulino",
"Kuzma",
"Uladz",
"Junko",
"Napaleo",
"Leu",
"Lew",
"Rhyn",
"Chanche",
"Lavazzi",
"Jaber",
"Fekyr",
"Taha",
"Tamakmul",
"Manrous",
"Ousmat",
"Toumats",
"Rifuan",
"Faruhi",
"Alit",
"Fauiz",
"Ahdat",
"Fandar",
"Chimo",
"Mohol",
"Jafiy",
"Gonles",
"Lipeng",
"Onjez",
"Inez",
"Kambul",
"Mapus",
"Rabad",
"Torsel",
"Tiers",
"Enwir",
"Woster",
"Owel",
"Eillion",
"Moship",
"Nisi",
"Derer",
"Garron",
"Moho",
"Dhev",
"Radom",
"Ethmet",
"Mehmir",
"Miccal",
"Tipper",
"Suss",
"Liesse",
"Utto",
"Leon",
"Merrin",
"Clythe",
"Charlette",
"Yvette",
"Yves",
"Merie",
"Erienne",
"Leann",
"Joan",
"Florian",
"Egwind",
"Ten",
"Vieng",
"Wilhuff",
"Orchart",
"Phoebe",
"Anise",
"Birgit",
"Enger",
"Veera",
"Hanne",
];

var arrOccupation= [
"Architect",
"Chandler",
"shipwright",
"clerk",
"magistrate",
"broker",
"weaver",
"carrier",
"carter",
"engineer",
"cleric",
"guard",
"messsenger",
"advocate",
"writ-carrier",
"speaker",
"herald",
"journalist",
"tanner",
"dyer",
"Hawker",
"Tinker",
"Labourer",
"Musician",
"Assassin",
"Cook",
"Sailor",
"miner",
"housekeeper",
"domestic",
"servant",
"factory worker",
"investor",
"landowner",
"nobleperson",
"beadle",
"deacon",
"shopkeeper",
"fishmonger",
"slaughterperson",
"farmer",
"woodcutter",
"charcoal burner",
"customs agent",
"politician",
"iron monger",
"clock maker",
"paper maker",
"bookbinder",
"printer",
"brickmaker",
"potter",
"silverworker",
"wetnurse",
"doctor",
"glass-breaker",
"spiritualist",
"apothecary",
"barber",
"animalist",
"zoo-keeper",
"internist",
"speaker to ghosts",
"rogue",
"gigolo",
"sex-worker",
"radical",
"teacher",
"lecturer",
"childminder",
"sweetmaker",
"bacterist",
"charlatan",
"coffee roaster",
"brewer",
"winemaker",
"smokehouser",
"chancellor",
"clerk",
"auditor",
"dunghauler",
"Costermonger",
"Carpenter",
"Thatcher",
"Tiler",
"Mosaic Artist",
"Vexatious Litigant",
"Water Diviner",
"Ganrdener",
"Arborist",
"Herbalist",
"Cottager",
"Crofter",
"Sherpherd",
"Bird Catcher",
"Angler",
"Eel Seller",
"Temple Guardian",
"Sin Eater",
"Shaman",
"Priest",
"Incense Grinder",
"Spice Taster",
"Sommelier",
"Assayer of gems and metals",
"Taster",
"Printer's assistant",
"Copyist",
"Editor",
"Joiner",
"Woodturner",
"Nail Cutter",
"Smith",
"Miller",
"Grocer",
"Draper",
"Milliner",
"Furrier",
"Auctioneer",
"Bookkeeper",
"gambling house keeper",
"Tavern Keeper",
"Smuggler",
"Vagabond",
"Baker",
"Pastry Cook",
"Bailiff",
"Reeve at Arms",
"Watch Keeper",
"Place Holder",
"Landlord",
"Hired Thug",
"Gunsmith",
"Fletcher",
"Armourer",
"Cannon Founder",
"Foundry worker",
"Coal-stoker",
"Place-filler",
"Dancer",
"Beggar",
"Gleaner",
"Muck Dragger",
"Dredge Trawler",
"Lumber seller",
"Basket weaver",
"Censor",
"Dog catcher",
"Refuse collector",
"Night soil carrier",
"Midwife",
"Nurse",
"Lady's companion",
"Gin steamer",
"Druggist",
"Drug house keeper",
"Griddle cleaner",
"Street sweeper",
"Grass mower",
"Dog trainer",
"Circus worker",
"Cog founder",
"Carnival operator",
"Sugarplum maker",
"Book reviewer",
"Crepe seller",
"Florist",
"Posy-seller",
"Match-seller",
"Ink-seller",
"Pan-repairer",
"Ostler",
"Carriage repairer",
"Groom",
"Sandwich seller",
"Advertiser",
"Poster sticker",
"Ice seller",
"Prize fighter",
"Knife Sharpener",
"Cobbler",
"Spectacle Maker",
"Bellringer",
"Housedresser",
"Estate Agent",
"Chorister",
"Ammanuensis",
"Docent",
"Fry cook",
"Pork roaster",
"Wheelwright",
"Gravedigger",
"Professional mourner",
"Mason",
"Clothes launderer",
"Banker",
"Beekeeper",
"Aviarist",
"Gosherd",
"Swineherd",
"Trinketeer",
"Engraver",
"Illustrator",
"Muralist",
"Juggler",
"Sculptor",
"Oil skimmer",
"Wagoneer",
"Maker of paper dolls",
"Kite seller",
"Doll maker",
"Toy soldier founder",
"Card shark",
"Shell diver",
"Tide picker",
"Chartier",
"Mapmaker",
"Surveyor",
"Flag embroiderer",
"Paint seller",
"Furniture seller",
"Butler",
"Valet",
"Organ grinder",
"Bear dancer",
"Monkey trainer",
"Vote faker",
"House steward",
"Bowyer",
"Cooper",
"Soapmaker",
"Storyteller",
"Interpreter",
"Translator",
"Tout",
"Fence",
"Counterfeiter",
"Mancatcher",
"Bounty agent",
"Astronomer",
"Card oracle",
"Salted piglet man",
"Squid catcher",
"Picture hanger",
"paper hanger",
"Rat Catcher",
"Calendarist",
"Calculator",
"Dramatist",
"Actor",
"Lifeboat rower",
"Barge puller",
"Deckhand",
"Dockhand",
"Doctor's fetchling",
"Water seller",
"Tattooist",
"Storyteller",
"Puppet maker",
"Puppetteer",
"Street painter",
"Chalk artist",
"Diplomat",
"Fortuner teller",
"Palmist",
"Distiller",
"Masseuse",
"Bone setter",
"Consulting linguist",
"Seal setter",
"Seal carver",
"Glazier",
"Layabout",
"Lounger",
"Idler",
"Scraper",
"Bootbrush",
"Coatchecker",
"Wool brusher",
"Yarn twister",
"Loom setter",
"Lens Grinder",
"Microscopist",
"Bowel washer",
"Vote-getter",
"Doorman",
"Archivist",
"Librarian",
"House mover",
"Bracefitter",
"Corsetiere",
"Lingeriere",
"Lacemaker",
"Crocheter",
"Agronomist",
"Hermit",
"Reasoner",
"Lighthouse Keeper",
"Lamplighter",
"Tootchcaster",
"Weatherwatcher",
"Place-keeper",
"Night cart puller",
"Paid agitator",
"trinketeer"
];

var arrObsession= [
"straightening old spoons",
"carrying grave earth in their pocket",
"keeping up with the laundry",
"the noise made by local dogs",
"the feel of well-kept leather",
"electromagnetism",
"storms, the properties of clouds and the manner in which weather is formed",
"magic",
"ways to cjeat at cards",
"port wine",
"the trading tables",
"horse racing",
"collecting rubbish",
"brushing their hair",
"diseases",
"cleanliness",
"saving money",
"clippping their nails",
"economising on boot polish",
"where parrots can be got for cheap",
"whether wild dogs roam the gardens and common grounds after dark",
"untested medicines",
"their health",
"whether they are getting enough sleep",
"saving money by reusing tobacco",
"dining at fine clubs and restaurants",
"pork",
"coffee",
"ritual observance",
"toasted cheese",
"avoiding sunburn",
"whether other people can see their wrinkles",
"aged persons, and in particular the way their skin crinkles and folds",
"clouds",
"the formation of gems and stones",
"mirrors",
"childrens toys",
"windmills",
"plaster casts",
"wax",
"bodily fluids",
"wallpaper",
"rusted nails",
"finding a good place to get cheap ink",
"politics",
"celebrities",
"famous criminals",
"torn pieces of coloured paper found on the street",
"the bones of your hand",
"Shadows and sunlight",
"counting the days left in the season",
"preventing te rise of dark powers in the land",
"revanchist nationalism",
"the overthrow of religious authority",
"the overthrow of political authority",
"bettering their social position",
"becoming a noted storyteller",
"flies",
"spiders",
"the hair of cats",
"various songs crowed by different roosters",
"the loudness or nearness of church bells",
"touching strangers' coats",
"the age of the world",
"whether there might be truth in the old legends",
"the doom they know to haunt their family",
"imagined slights",
"becoming a noted dandy",
"becoming a famous beauty",
"the aristocracy and their lifestyles",
"the ways of the poor",
"new techniques of baking bread",
"cleaning their clothes",
"the possibility of powered flight",
"warfare and strategy",
"Burnt pots",
"Fingernail dirt",
"Farts",
"The strength of various balloons",
"Finding a lost treasure known only to a secret society to which they do not belong.",
"Erotic art",
"Going through their neighbours' rubbish",
"A potential pretender to the throne",
"Holidaying in the mountains",
"Walking under moonlight",
"Fishing",
"Trying every new chocolate in the town",
"Finding the best way to erect a tent",
"Keeping their trouser creases parallel",
"Making a durable pair of paper shoes",
"Chewing on dirt",
"Spitting whenever they see a bird or a lamppost",
"Eatingtwigs of various aromatc woods",
"Tasting different tobaccos",
"Finding the perfect pillow",
"The existence of particular undiscovered lands",
"The location of fabled, lost cities",
"Finding a passage through the Leggio d'Antigueys",
"Picking and arranging wildflowers",
"Catching grasshoppers",
"Killing flies",
"Chasing every mouse they see",
"Chasing scraps of paper blown by the wind",
"Famous criminals",
"Famous church figures",
"Stealing from beggars' bowls",
"Making cider",
"drinking more slowly than their fellows",
"Their weight",
"whether they are going bald",
"Whether they have had a hex put on them",
"finding rats in the storeroom",
"stealing from their neighbours",
"the notion that their neighbours are secretly watching them",
"learning how to do card tricks",
"recounting famous battles from the past",
"talking to strangers in public carriages",
"complaining to stewards about things beyond their control",
"whether the traffic is flowing well on the rivers",
"the rate of tax",
"the rate of excise",
"having pipe smoking outlawed",
"the price of fish at market",
"the price of a hundredweight of barley on the exchanges",
"whether their neighbour secretly keeps geese in a partition of the common attic",
"The cleanliness of the streets",
"whether cattle and sheep owned by religious orders ought to be allowed to graze on common ground",
"making appeals to various courts to open up byways and paths which have been closed off by new building",
"harrassing the nightcart man",
"ways to win at cards",
"writing letters to the editors of local journals on philosophical matters",
"petitioning the chancel to do something about didicot men",
"shouting at tinkers and street traders",
"disrupting street performances",
"teaching a pig to sing",
"seeing an injury to their pride revenged",
"Overturning an unjust law that targets pedlars of pipe tobacco",
"Collecting the lyrics of rare sailors jigs and ditties",
"ensuring the books on any shelf are just perfectly straight and in line with the edge",
"Arranging small objects in lines or shapes",
"Picking wildflowers",
"Pressing insects and mounting them in little boxes",
"Brewing a sort of pickle out of cabbages, quince and pear",
"Recording every throw of the dice they ever make and trying to find patterns among them",
"Developing a perfect historical system that will explain the rise and fall of the great powers of antiquity and predict future events",
"Finding a way to have automata speak and make decisions",
"The perceived wastefulness of local bureaucracy",
"The perceived tendency of the local burghers and beadlerie towards censorship",
"whether people think they have small hands",
"Whether one of their eyes is larger than the other",
"whether dogs can be amde to understand human speech",
"Whether cats can be made to sing in tune",
"Whether mice have in them the capacity of reason",
"A curriculum for the perfect moral education of children",
"The possibility of a further prophet to be found among the lower orders, who will reveal the folly of all established religion",
"Whether there might truly be great and heavy calves with sweet meat and gentle temper who stroll about on the moon, eating sunbeams",
"Whether it is posion to eat the green parts of a potato once it has been cooked",
"Chasing away ragabout children from the door of their house",
"harrassing the tellers of fortunes to get free readings of their future",
"knowing the horoscope of any person who they might meet",
"Telling people their dreams and asking whether those dreams seem odd.",
"Comparing the speed at which their hair grows to that other people",
"Finding a way to patch their cuffs without it being obvious",
"how many persons a dog or a cat can recognise",
"a sure-fire plan for wealth creation they were told about ina  tavern",
"a better way to get oil stains out of cloth garments",
"whether silkworms can be raced as are lice and dogs",
"Whether turtles might make a placid and loyal pet",
"Finding a better price for a brace of partridges than their neighbour",
"Being the first of their fellows to have read the news paper",
"finding the playbills of pennyfright plays and cutting out the pictures to stick on their wall",
"Being the first to hear the news from the pieman",
"programming an automaton to speak the language of birds",
"finding a cure for dog lice",
"determining a means of obtaining free massages from their landlord who has great, strong hands",
"keeping all the clippings of their nails in a little bag around their neck",
];

//generating a first and lat name from th names list

var randomNumberFirstName = Math.floor(Math.random() * arrNames.length);
var randomNumberLastName = Math.floor(Math.random() * arrNames.length);
var firstNameIndex = randomNumberFirstName;
var lastNameIndex = randomNumberLastName
var characterFirstName = arrNames[firstNameIndex];
var characterFirstName1A = characterFirstName.concat(" ") 
var characterLastName = arrNames[lastNameIndex];
var fullName = characterFirstName1A.concat(characterLastName);

//calculating an age

var ageRaw = Math.floor(Math.random() * 71);
var age = ageRaw+21;

//generating and occupation from the occupations list

var randomNumberOccupation = Math.floor(Math.random() * arrOccupation.length);
var occupationIndex = randomNumberOccupation;
var occupation = arrOccupation[occupationIndex]; 

//generating an obsession from the obsessions array

var randomNumberObsession = Math.floor(Math.random() * arrObsession.length);
var obsessionIndex = randomNumberObsession;
var obsession = arrObsession[obsessionIndex]; 

//combining all of the attributes into a string

var characterPrint = fullName + ", aged " + age + ", is a " + occupation + ". They are obsessed with " + obsession + ".";

//printing the string of character attributes to an element

document.getElementById("characterAnswer").innerHTML = characterPrint;
}

characterGen();
